name: weathered
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  dynamic_color: ^1.6.9
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  gap: ^3.0.1
  material_color_utilities: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^2.3.9
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets: 
    - assets/fonts/
# Fonts have been taken from fonts.google.com
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
